I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 6, in script
    init python:
  File "game/script.rpy", line 6, in script
    init python:
  File "game/script.rpy", line 7, in <module>
    import sqlite3 as sql
ImportError: No module named sqlite3

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "/home/colton/Github/renpy-7.4.11-sdk/renpy/bootstrap.py", line 331, in bootstrap
    renpy.main.main()
  File "/home/colton/Github/renpy-7.4.11-sdk/renpy/main.py", line 560, in main
    renpy.game.context().run(node)
  File "game/script.rpy", line 6, in script
    init python:
  File "game/script.rpy", line 6, in script
    init python:
  File "/home/colton/Github/renpy-7.4.11-sdk/renpy/ast.py", line 928, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/home/colton/Github/renpy-7.4.11-sdk/renpy/python.py", line 2245, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 7, in <module>
    import sqlite3 as sql
ImportError: No module named sqlite3

Linux-5.13.0-35-generic-x86_64-with-debian-bullseye-sid
Ren'Py 7.4.11.2266
SOC409 1.0
Sat Mar 12 20:29:13 2022
